"""Update DB to save epayco payments

Revision ID: f24c69d1e8d3
Revises: b0b1b2281c34
Create Date: 2025-05-27 03:53:52.269522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f24c69d1e8d3'
down_revision: Union[str, None] = 'b0b1b2281c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('epayco_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('epayco_response_code', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('epayco_response_message', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('epayco_approval_code', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('epayco_receipt', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('card_last_four', sa.String(length=4), nullable=True))
    op.add_column('payments', sa.Column('card_brand', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('client_name', sa.String(length=200), nullable=True))
    op.add_column('payments', sa.Column('client_email', sa.String(length=200), nullable=True))
    op.add_column('payments', sa.Column('client_phone', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('client_ip', postgresql.INET(), nullable=True))
    op.add_column('payments', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'processed_at')
    op.drop_column('payments', 'client_ip')
    op.drop_column('payments', 'client_phone')
    op.drop_column('payments', 'client_email')
    op.drop_column('payments', 'client_name')
    op.drop_column('payments', 'card_brand')
    op.drop_column('payments', 'card_last_four')
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'epayco_receipt')
    op.drop_column('payments', 'epayco_approval_code')
    op.drop_column('payments', 'epayco_response_message')
    op.drop_column('payments', 'epayco_response_code')
    op.drop_column('payments', 'epayco_transaction_id')
    # ### end Alembic commands ###
